services:
  blockchain:
    container_name: blockchain-fork
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    # restart: unless-stopped
    tty: true
    mem_limit: 4GB
    ports:
      - "8545:8545"
    env_file:
      - .env
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: blockchain-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - blockchain
    env_file:
      - .env
